// Code generated by MockGen. DO NOT EDIT.
// Source: domain/company/usecase/company.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	entity "gitlab.warungpintar.co/sales-platform/brook/domain/company/entity"
)

// MockServiceManager is a mock of ServiceManager interface.
type MockServiceManager struct {
	ctrl     *gomock.Controller
	recorder *MockServiceManagerMockRecorder
}

// MockServiceManagerMockRecorder is the mock recorder for MockServiceManager.
type MockServiceManagerMockRecorder struct {
	mock *MockServiceManager
}

// NewMockServiceManager creates a new mock instance.
func NewMockServiceManager(ctrl *gomock.Controller) *MockServiceManager {
	mock := &MockServiceManager{ctrl: ctrl}
	mock.recorder = &MockServiceManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockServiceManager) EXPECT() *MockServiceManagerMockRecorder {
	return m.recorder
}

// CompanyRegister mocks base method.
func (m *MockServiceManager) CompanyRegister(ctx context.Context, companyData *entity.Company) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CompanyRegister", ctx, companyData)
	ret0, _ := ret[0].(error)
	return ret0
}

// CompanyRegister indicates an expected call of CompanyRegister.
func (mr *MockServiceManagerMockRecorder) CompanyRegister(ctx, companyData interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CompanyRegister", reflect.TypeOf((*MockServiceManager)(nil).CompanyRegister), ctx, companyData)
}
