// Code generated by MockGen. DO NOT EDIT.
// Source: domain/user/repository/repository.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	entity "gitlab.warungpintar.co/sales-platform/brook/domain/user/entity"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// UserActivation mocks base method.
func (m *MockRepository) UserActivation(ctx context.Context, userData *entity.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UserActivation", ctx, userData)
	ret0, _ := ret[0].(error)
	return ret0
}

// UserActivation indicates an expected call of UserActivation.
func (mr *MockRepositoryMockRecorder) UserActivation(ctx, userData interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UserActivation", reflect.TypeOf((*MockRepository)(nil).UserActivation), ctx, userData)
}

// UserRegister mocks base method.
func (m *MockRepository) UserRegister(ctx context.Context, userData *entity.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UserRegister", ctx, userData)
	ret0, _ := ret[0].(error)
	return ret0
}

// UserRegister indicates an expected call of UserRegister.
func (mr *MockRepositoryMockRecorder) UserRegister(ctx, userData interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UserRegister", reflect.TypeOf((*MockRepository)(nil).UserRegister), ctx, userData)
}
