// Code generated by MockGen. DO NOT EDIT.
// Source: domain/repository/repository.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	gomock "github.com/golang/mock/gomock"
	entity "gitlab.warungpintar.co/sales-platform/brook/domain/entity"
	reflect "reflect"
)

// MockRepository is a mock of Repository interface
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// FindOrder mocks base method
func (m *MockRepository) FindOrder(ctx context.Context) ([]*entity.OrderAggregate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindOrder", ctx)
	ret0, _ := ret[0].([]*entity.OrderAggregate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindOrder indicates an expected call of FindOrder
func (mr *MockRepositoryMockRecorder) FindOrder(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOrder", reflect.TypeOf((*MockRepository)(nil).FindOrder), ctx)
}
