// Code generated by MockGen. DO NOT EDIT.
// Source: domain/company/repository/repository.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	entity "gitlab.warungpintar.co/sales-platform/brook/domain/company/entity"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// CompanyRegister mocks base method.
func (m *MockRepository) CompanyRegister(ctx context.Context, companyData *entity.Company) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CompanyRegister", ctx, companyData)
	ret0, _ := ret[0].(error)
	return ret0
}

// CompanyRegister indicates an expected call of CompanyRegister.
func (mr *MockRepositoryMockRecorder) CompanyRegister(ctx, companyData interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CompanyRegister", reflect.TypeOf((*MockRepository)(nil).CompanyRegister), ctx, companyData)
}
