// Code generated by MockGen. DO NOT EDIT.
// Source: domain/otp/repository/repository.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	entity "gitlab.warungpintar.co/sales-platform/brook/domain/otp/entity"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// CreateOrUpdateOtp mocks base method.
func (m *MockRepository) CreateOrUpdateOtp(ctx context.Context, userData *entity.Otp) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOrUpdateOtp", ctx, userData)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateOrUpdateOtp indicates an expected call of CreateOrUpdateOtp.
func (mr *MockRepositoryMockRecorder) CreateOrUpdateOtp(ctx, userData interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOrUpdateOtp", reflect.TypeOf((*MockRepository)(nil).CreateOrUpdateOtp), ctx, userData)
}

// FindOtp mocks base method.
func (m *MockRepository) FindOtp(ctx context.Context, employeeId, otpType string) (*entity.Otp, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindOtp", ctx, employeeId, otpType)
	ret0, _ := ret[0].(*entity.Otp)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindOtp indicates an expected call of FindOtp.
func (mr *MockRepositoryMockRecorder) FindOtp(ctx, employeeId, otpType interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOtp", reflect.TypeOf((*MockRepository)(nil).FindOtp), ctx, employeeId, otpType)
}
