// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package adapter

import (
	mock "github.com/stretchr/testify/mock"
	gorm "gorm.io/gorm"
)

// mockGormOpenInterface is an autogenerated mock type for the gormOpenInterface type
type mockGormOpenInterface struct {
	mock.Mock
}

// GetOriginal provides a mock function with given fields:
func (_m *mockGormOpenInterface) GetOriginal() *gorm.DB {
	ret := _m.Called()

	var r0 *gorm.DB
	if rf, ok := ret.Get(0).(func() *gorm.DB); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gorm.DB)
		}
	}

	return r0
}

// OpenConnection provides a mock function with given fields: dbcfg, gormcfg
func (_m *mockGormOpenInterface) OpenConnection(dbcfg Config, gormcfg *gorm.Config) (gormdb, error) {
	ret := _m.Called(dbcfg, gormcfg)

	var r0 gormdb
	if rf, ok := ret.Get(0).(func(Config, *gorm.Config) gormdb); ok {
		r0 = rf(dbcfg, gormcfg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(gormdb)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(Config, *gorm.Config) error); ok {
		r1 = rf(dbcfg, gormcfg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
