// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package adapter

import (
	sql "database/sql"

	mock "github.com/stretchr/testify/mock"
	gorm "gorm.io/gorm"
)

// mockGormdb is an autogenerated mock type for the gormdb type
type mockGormdb struct {
	mock.Mock
}

// DB provides a mock function with given fields:
func (_m *mockGormdb) DB() (*sql.DB, error) {
	ret := _m.Called()

	var r0 *sql.DB
	if rf, ok := ret.Get(0).(func() *sql.DB); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sql.DB)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Use provides a mock function with given fields: plugin
func (_m *mockGormdb) Use(plugin gorm.Plugin) error {
	ret := _m.Called(plugin)

	var r0 error
	if rf, ok := ret.Get(0).(func(gorm.Plugin) error); ok {
		r0 = rf(plugin)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
