// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package adapter

import (
	mock "github.com/stretchr/testify/mock"
	gorm "gorm.io/gorm"
)

// MockGormStarter is an autogenerated mock type for the GormStarter type
type MockGormStarter struct {
	mock.Mock
}

// ConnectToGorm provides a mock function with given fields: dbcfg, gormcfg
func (_m *MockGormStarter) ConnectToGorm(dbcfg Config, gormcfg *gorm.Config) (*gorm.DB, error) {
	ret := _m.Called(dbcfg, gormcfg)

	var r0 *gorm.DB
	if rf, ok := ret.Get(0).(func(Config, *gorm.Config) *gorm.DB); ok {
		r0 = rf(dbcfg, gormcfg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gorm.DB)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(Config, *gorm.Config) error); ok {
		r1 = rf(dbcfg, gormcfg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
